// Copyright 2022 Monoskope Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file api/eventsourcing/eventdata/test.proto (package eventdata, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message eventdata.TestEventData
 */
export class TestEventData extends Message<TestEventData> {
  /**
   * @generated from field: string hello = 1;
   */
  hello = "";

  constructor(data?: PartialMessage<TestEventData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "eventdata.TestEventData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "hello", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestEventData {
    return new TestEventData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestEventData {
    return new TestEventData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestEventData {
    return new TestEventData().fromJsonString(jsonString, options);
  }

  static equals(a: TestEventData | PlainMessage<TestEventData> | undefined, b: TestEventData | PlainMessage<TestEventData> | undefined): boolean {
    return proto3.util.equals(TestEventData, a, b);
  }
}

