/**
 * @fileoverview gRPC-Web generated client stub for eventsourcing
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.2
// source: api/eventsourcing/commandhandler_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var api_eventsourcing_commands_command_pb = require('../../api/eventsourcing/commands/command_pb.js')

var validate_validate_pb = require('../../validate/validate_pb.js')
const proto = {};
proto.eventsourcing = require('./commandhandler_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.eventsourcing.CommandHandlerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.eventsourcing.CommandHandlerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.commands.Command,
 *   !proto.eventsourcing.CommandReply>}
 */
const methodDescriptor_CommandHandler_Execute = new grpc.web.MethodDescriptor(
  '/eventsourcing.CommandHandler/Execute',
  grpc.web.MethodType.UNARY,
  api_eventsourcing_commands_command_pb.Command,
  proto.eventsourcing.CommandReply,
  /**
   * @param {!proto.commands.Command} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.eventsourcing.CommandReply.deserializeBinary
);


/**
 * @param {!proto.commands.Command} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.eventsourcing.CommandReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.eventsourcing.CommandReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.eventsourcing.CommandHandlerClient.prototype.execute =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/eventsourcing.CommandHandler/Execute',
      request,
      metadata || {},
      methodDescriptor_CommandHandler_Execute,
      callback);
};


/**
 * @param {!proto.commands.Command} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.eventsourcing.CommandReply>}
 *     Promise that resolves to the response
 */
proto.eventsourcing.CommandHandlerPromiseClient.prototype.execute =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/eventsourcing.CommandHandler/Execute',
      request,
      metadata || {},
      methodDescriptor_CommandHandler_Execute);
};


module.exports = proto.eventsourcing;

