/**
 * @fileoverview gRPC-Web generated client stub for eventsourcing
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.2
// source: api/eventsourcing/eventstore_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var api_eventsourcing_messages_pb = require('../../api/eventsourcing/messages_pb.js')
const proto = {};
proto.eventsourcing = require('./eventstore_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.eventsourcing.EventStoreClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.eventsourcing.EventStorePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.eventsourcing.EventFilter,
 *   !proto.eventsourcing.Event>}
 */
const methodDescriptor_EventStore_Retrieve = new grpc.web.MethodDescriptor(
  '/eventsourcing.EventStore/Retrieve',
  grpc.web.MethodType.SERVER_STREAMING,
  api_eventsourcing_messages_pb.EventFilter,
  api_eventsourcing_messages_pb.Event,
  /**
   * @param {!proto.eventsourcing.EventFilter} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  api_eventsourcing_messages_pb.Event.deserializeBinary
);


/**
 * @param {!proto.eventsourcing.EventFilter} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.eventsourcing.Event>}
 *     The XHR Node Readable Stream
 */
proto.eventsourcing.EventStoreClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/eventsourcing.EventStore/Retrieve',
      request,
      metadata || {},
      methodDescriptor_EventStore_Retrieve);
};


/**
 * @param {!proto.eventsourcing.EventFilter} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.eventsourcing.Event>}
 *     The XHR Node Readable Stream
 */
proto.eventsourcing.EventStorePromiseClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/eventsourcing.EventStore/Retrieve',
      request,
      metadata || {},
      methodDescriptor_EventStore_Retrieve);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.eventsourcing.EventFilters,
 *   !proto.eventsourcing.Event>}
 */
const methodDescriptor_EventStore_RetrieveOr = new grpc.web.MethodDescriptor(
  '/eventsourcing.EventStore/RetrieveOr',
  grpc.web.MethodType.SERVER_STREAMING,
  api_eventsourcing_messages_pb.EventFilters,
  api_eventsourcing_messages_pb.Event,
  /**
   * @param {!proto.eventsourcing.EventFilters} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  api_eventsourcing_messages_pb.Event.deserializeBinary
);


/**
 * @param {!proto.eventsourcing.EventFilters} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.eventsourcing.Event>}
 *     The XHR Node Readable Stream
 */
proto.eventsourcing.EventStoreClient.prototype.retrieveOr =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/eventsourcing.EventStore/RetrieveOr',
      request,
      metadata || {},
      methodDescriptor_EventStore_RetrieveOr);
};


/**
 * @param {!proto.eventsourcing.EventFilters} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.eventsourcing.Event>}
 *     The XHR Node Readable Stream
 */
proto.eventsourcing.EventStorePromiseClient.prototype.retrieveOr =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/eventsourcing.EventStore/RetrieveOr',
      request,
      metadata || {},
      methodDescriptor_EventStore_RetrieveOr);
};


module.exports = proto.eventsourcing;

