// Copyright 2022 Monoskope Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-connect-web v0.7.0 with parameter "target=ts,import_extension=none"
// @generated from file api/domain/commandhandler_service.proto (package domain, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { PermissionModel } from "./commandhandler_service_pb";

/**
 * API extensions of the Monoskope CommandHandler.
 *
 * @generated from service domain.CommandHandlerExtensions
 */
export const CommandHandlerExtensions = {
  typeName: "domain.CommandHandlerExtensions",
  methods: {
    /**
     * Returns roles and scopes available.
     *
     * @generated from rpc domain.CommandHandlerExtensions.GetPermissionModel
     */
    getPermissionModel: {
      name: "GetPermissionModel",
      I: Empty,
      O: PermissionModel,
      kind: MethodKind.Unary,
    },
  }
} as const;

