/**
 * @fileoverview gRPC-Web generated client stub for domain
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.2
// source: api/domain/commandhandler_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as api_domain_commandhandler_service_pb from '../../api/domain/commandhandler_service_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';


export class CommandHandlerExtensionsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetPermissionModel = new grpcWeb.MethodDescriptor(
    '/domain.CommandHandlerExtensions/GetPermissionModel',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    api_domain_commandhandler_service_pb.PermissionModel,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    api_domain_commandhandler_service_pb.PermissionModel.deserializeBinary
  );

  getPermissionModel(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<api_domain_commandhandler_service_pb.PermissionModel>;

  getPermissionModel(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_domain_commandhandler_service_pb.PermissionModel) => void): grpcWeb.ClientReadableStream<api_domain_commandhandler_service_pb.PermissionModel>;

  getPermissionModel(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_domain_commandhandler_service_pb.PermissionModel) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/domain.CommandHandlerExtensions/GetPermissionModel',
        request,
        metadata || {},
        this.methodDescriptorGetPermissionModel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/domain.CommandHandlerExtensions/GetPermissionModel',
    request,
    metadata || {},
    this.methodDescriptorGetPermissionModel);
  }

}

