/**
 * @fileoverview gRPC-Web generated client stub for domain
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.2
// source: api/domain/commandhandler_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var validate_validate_pb = require('../../validate/validate_pb.js')
const proto = {};
proto.domain = require('./commandhandler_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domain.CommandHandlerExtensionsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.domain.CommandHandlerExtensionsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.domain.PermissionModel>}
 */
const methodDescriptor_CommandHandlerExtensions_GetPermissionModel = new grpc.web.MethodDescriptor(
  '/domain.CommandHandlerExtensions/GetPermissionModel',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.domain.PermissionModel,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.domain.PermissionModel.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.domain.PermissionModel)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.domain.PermissionModel>|undefined}
 *     The XHR Node Readable Stream
 */
proto.domain.CommandHandlerExtensionsClient.prototype.getPermissionModel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/domain.CommandHandlerExtensions/GetPermissionModel',
      request,
      metadata || {},
      methodDescriptor_CommandHandlerExtensions_GetPermissionModel,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.domain.PermissionModel>}
 *     Promise that resolves to the response
 */
proto.domain.CommandHandlerExtensionsPromiseClient.prototype.getPermissionModel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/domain.CommandHandlerExtensions/GetPermissionModel',
      request,
      metadata || {},
      methodDescriptor_CommandHandlerExtensions_GetPermissionModel);
};


module.exports = proto.domain;

