name: Helm CI

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

env:
  HELM_PATH: build/package/helm

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: lint helm
        run: |
          make helm-lint
