// Copyright 2022 Monoskope Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file api/domain/eventdata/user.proto (package eventdata, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { UserSource } from "../common/messages_pb.js";

/**
 * @generated from message eventdata.UserCreated
 */
export class UserCreated extends Message<UserCreated> {
  /**
   * Email address of the user
   *
   * @generated from field: string email = 1;
   */
  email = "";

  /**
   * Name of the user
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * Source the user originates from, e.g. "monoskope"
   *
   * @generated from field: common.UserSource source = 3;
   */
  source = UserSource.INTERNAL;

  constructor(data?: PartialMessage<UserCreated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "eventdata.UserCreated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "source", kind: "enum", T: proto3.getEnumType(UserSource) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserCreated {
    return new UserCreated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserCreated {
    return new UserCreated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserCreated {
    return new UserCreated().fromJsonString(jsonString, options);
  }

  static equals(a: UserCreated | PlainMessage<UserCreated> | undefined, b: UserCreated | PlainMessage<UserCreated> | undefined): boolean {
    return proto3.util.equals(UserCreated, a, b);
  }
}

/**
 * @generated from message eventdata.UserRoleAdded
 */
export class UserRoleAdded extends Message<UserRoleAdded> {
  /**
   * Unique identifier of the user (UUID 128-bit number)
   *
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * Name of the role added to the user
   *
   * @generated from field: string role = 2;
   */
  role = "";

  /**
   * Scope of the role
   *
   * @generated from field: string scope = 3;
   */
  scope = "";

  /**
   * Unique identifier of the affected resource (UUID 128-bit number)
   *
   * @generated from field: string resource = 4;
   */
  resource = "";

  constructor(data?: PartialMessage<UserRoleAdded>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "eventdata.UserRoleAdded";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "scope", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "resource", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserRoleAdded {
    return new UserRoleAdded().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserRoleAdded {
    return new UserRoleAdded().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserRoleAdded {
    return new UserRoleAdded().fromJsonString(jsonString, options);
  }

  static equals(a: UserRoleAdded | PlainMessage<UserRoleAdded> | undefined, b: UserRoleAdded | PlainMessage<UserRoleAdded> | undefined): boolean {
    return proto3.util.equals(UserRoleAdded, a, b);
  }
}

/**
 * @generated from message eventdata.UserUpdated
 */
export class UserUpdated extends Message<UserUpdated> {
  /**
   * Name of the user
   *
   * @generated from field: string name = 2;
   */
  name = "";

  constructor(data?: PartialMessage<UserUpdated>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "eventdata.UserUpdated";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserUpdated {
    return new UserUpdated().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserUpdated {
    return new UserUpdated().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserUpdated {
    return new UserUpdated().fromJsonString(jsonString, options);
  }

  static equals(a: UserUpdated | PlainMessage<UserUpdated> | undefined, b: UserUpdated | PlainMessage<UserUpdated> | undefined): boolean {
    return proto3.util.equals(UserUpdated, a, b);
  }
}

